### ISSUE TITLE
Can't access host filesystem from open-file dialog

### ISSUE THREAD

**Issue by n8willis** [flathub/org.fontforge.FontForge#12]
For whatever reason, the flathub pakage of FontForge is not able to see files & directories in the host filesystem, at least not when opening a font via the file menu item.

I am clear that the `--filesystem=host` configuration option *is* set in the pak YAML file since 46335f5f205a13c22892d9b180f574f3897dfe3a but it is painfully clear that the file-selection dialog is *not* seeing the full /usr/share/fonts/ directory on my system when I try to open a font. Here's reality, via the Apt-supplied FonfForge binary:
![ff-filechooser-reallife](https://user-images.githubusercontent.com/2192132/101938904-14a2f580-3bdc-11eb-9a81-f7ce35447d7f.png)

And here's what the pak sees:
![ff-filechooser-flatpak](https://user-images.githubusercontent.com/2192132/101938911-1967a980-3bdc-11eb-859e-7f03921fe72e.png)

Based on the contents of what it _is_ seeing, the chooser is only able to access the FD.o runtime:
![runtime-dir](https://user-images.githubusercontent.com/2192132/101939265-a7439480-3bdc-11eb-82be-713bf429c851.png)

Since the bulk of what I use FontForge for at present is inspecting and analyzing fonts, that makes this bug a serious impediment.

**Comment by muelli** [comment]
Hi Nate, nice to read you :)
Yeah, `/usr` comes from the runtime, AFAIK. Can you check `/run/host/usr/share/fonts/`?

**Comment by muelli** [comment]
please re-open if this is still an issue.

**Comment by n8willis** [comment]
For the sake of future users who encounter the same problem and find this: the suggestion did *not* work. I stopped using the Flathub package entirely, because that package did not work.

So, even though this issue may have been closed, do be clear that the problem was not fixed; just this issue was closed.

**Comment by hfiguiere** [comment]
the "problem" here is sandboxing and the assumption that an app can open random system files and get away with it. `/usr` inside the flatpak is the flatpak platform, it's read-only and definitely whatever the host has. It's the same for everyone. `host` will not make this work.

`host-os` allow to have it in `/run/host`

**Comment by n8willis** [comment]
> and the assumption that an app can open random system files and get away with it. 

I'm not sure if I understand the wording of this part, but if you're saying that I made an "assumption" of some kind, then I definitively did not. There is a task that needs to be done; I attempt to do it; if this package of this application is unable to perform the task, then I stop using this package and go use a different package. That's the sequence of events.

If you're not saying that I made an "assumption", then never mind.

Either way, do note that I'm unsubscribing from this thread. Best of luck to future users reading here who may or may not have similar experiences with the tasks they're needing to do.

**Comment by hfiguiere** [comment]
not you (it's not personal), but app developers in general.

The UNIX philosophy and "let's use what the distro provides", and also mutable OS are assumptions that don't gel well with sandboxing.

There are plenty of challenges to resolve the issues, but I think it's time to rethink what should be doable, and IMHO an app that modifies `/usr` should be part of what's a negative.

**Comment by n8willis** [comment]
Okay.

Definitely worth thinking about those issues in general.

For my part, I feel it might be useful to comment that the operation which originally prompted this issue was about _reading_ system (or, non-/home) files, no modification involved. Even on an immutable system, there will always be occasions when the user needs to read a file, even if they're not needing to (or, possibly, should never be allowed to) write to that particular file.

So if some mechanism X for locking-off the filesystem in order to protecting it from writing _also_ makes it inaccessible for reading, then I believe it shows that mechanism X is not fitting the bill.
