### ISSUE TITLE
Is Python v2.7 required?

### ISSUE THREAD

**Issue by zefr0x** [flathub/org.fontforge.FontForge#23]
I found that Python 2.7 is included in the manifest:
https://github.com/flathub/org.fontforge.FontForge/blob/a3c5607a92d327303e8c76d6319943b07e285ab4/org.fontforge.FontForge.yaml#L22

But since [FontForge 2020 March Release](https://github.com/fontforge/fontforge/releases/tag/20200314):
> As part of the switch to CMake, per the deprecation of Python 2, and per the lack of objections to the proposal on the mailing list, we have dropped support for building FontForge with Python 2 support. The non-build-system Python 2 code remains, but it is neither tested nor maintained nor supported and is likely to follow a trajectory of decay and then removal.

And since [FontForge March 2022 Release](https://github.com/fontforge/fontforge/releases/tag/20220308):
> The minimum supported Python version is now Python 3.6

So, as I'm aware, python2 is no longer a dependency.

**Comment by muelli** [comment]
yep, seems to be a stale dependency. Thanks!
