### ISSUE TITLE
Not displayed in Store

### ISSUE THREAD

**Issue by Unrud** [flathub/org.fontforge.FontForge#3]
The app is missing: https://flathub.org/apps/details/org.fontforge.FontForge
Only the EOLed [io.github.Fontforge](https://flathub.org/apps/details/io.github.Fontforge) exists.

**Comment by muelli** [comment]
yeah, weird indeed.

The build job https://flathub.org/builds/#/builders/32/builds/1506 seems to have failed in the publish stage: https://flathub.org/builds/#/builders/29/builds/1096
That log is not very helpful though.

I've triggered a new build, but it fails with problems with the appdata https://flathub.org/builds/#/builders/19/builds/479 
```
 argv: b'flatpak run org.freedesktop.appstream-glib validate builddir/*/share/appdata/org.fontforge.FontForge.appdata.xml'
 using PTY: False
builddir/files/share/appdata/org.fontforge.FontForge.appdata.xml: FAILED:
• tag-missing           : <name> is not present
• tag-missing           : <summary> is not present
Validation of files failed
program finished with exit code 1
```

**Comment by muelli** [comment]
I have pushed a version which should have gotten published: https://flathub.org/builds/#/builders/32/builds/4044

I have mentioned the missing tags in https://github.com/fontforge/fontforge/issues/892#issuecomment-497018678

Let's hope that this makes it appear on https://flathub.org/apps/details/org.fontforge.FontForge

**Comment by muelli** [comment]
The app is still not visible.
The bot complained about the appdata file: https://flathub.org/builds/#/builders/48/builds/723
```
Removing files/bin/idle
Removing files/bin/easy_install-2.7
Removing files/bin/easy_install
Removing files/bin/2to3
Running appstream-compose
FB: Running: flatpak build --die-with-parent --nofilesystem=host /srv/buildbot/worker/build-x86_64/build/.flatpak-builder/rofiles/rofiles-B0itD6 appstream-compose --prefix=/app --origin=flatpak --basename=org.fontforge.FontForge org.fontforge.FontForge
Processing application org.fontforge.FontForge
Error loading AppData file: failed to parse /app/share/metainfo/org.fontforge.FontForge.metainfo.xml: Error on line 52 char 14: Odd character “l”, expected a “=” after attribute name “xml:” of element “p”
Error: ERROR: appstream-compose failed: Child process exited with code 1
FB: unmounting rofiles-fuse /srv/buildbot/worker/build-x86_64/build/.flatpak-builder/rofiles/rofiles-B0itD6
```
I have opened https://github.com/fontforge/fontforge/pull/3858 which will hopefully fix the problem.

**Comment by muelli** [comment]
Another problem is the name and summary tag of the current stable release, it seems:
https://flathub.org/builds/#/builders/19/builds/739
```
flatpak run org.freedesktop.appstream-glib validate builddir/*/share/appdata/org.fontforge.FontForge.appdata.xml
 in dir /srv/buildbot/worker/build-x86_64-7/build (timeout 1200 secs)
 watching logfiles {}
 argv: b'flatpak run org.freedesktop.appstream-glib validate builddir/*/share/appdata/org.fontforge.FontForge.appdata.xml'
 using PTY: False
builddir/files/share/appdata/org.fontforge.FontForge.appdata.xml: FAILED:
• tag-missing           : <name> is not present
• tag-missing           : <summary> is not present
Validation of files failed
program finished with exit code 1
elapsedTime=0.368309
```

I have opened https://github.com/fontforge/fontforge/pull/3859

**Comment by muelli** [comment]
And https://github.com/flathub/linux-store-backend/issues/21

**Comment by TingPing** [comment]
So the builders do complain more loudly now so this might be relevant:

```
builddir/files/share/appdata/org.fontforge.FontForge.appdata.xml: FAILED:
• url-not-found         : <screenshot> failed to download (HTTP 404: Not Found) [https://github.com/fontforge/fontforge/raw/master/doc/html/ff-screenshot.png]
Validation of files failed
```

**Comment by skierpage** [comment]
> I have opened [fontforge/fontforge#3859](https://github.com/fontforge/fontforge/pull/3859)

> local commit e9973e8 

Is it intentional that FontForge has two appdata source files (https://github.com/flathub/org.fontforge.FontForge/blob/master/org.fontforge.FontForge.appdata.xml and https://github.com/fontforge/fontforge/blob/master/desktop/org.fontforge.FontForge.appdata.xml.in )?

**Comment by muelli** [comment]
the appdata file is a relatively new thing for fontforge. We ought to use the upstream one. I have tried to upstream all the changes of the flathub appdata file.

**Comment by barthalion** [comment]
Apparently backend has its own internal limit for description and translations must have exceeded it.

```
Oct 22 22:12:00 webapps.flathub.org podman[3589]: 2019-10-22 22:12:00.660  WARN 6 --- [pool-2-thread-1] o.flathub.api.service.UpdateServiceImpl  : org.fontforge.FontForge has incomplete appdata and won't be added/updated in the webstore. Issues found:
Oct 22 22:12:00 webapps.flathub.org podman[3589]: 2019-10-22 22:12:00.660  WARN 6 --- [pool-2-thread-1] o.flathub.api.service.UpdateServiceImpl  :   - component.description is longuer than 4096
```

**Comment by muelli** [comment]
interesting indeed. We can probably shorten the description. But it would be good to expose that limitation to the build bots somehow.

**Comment by muelli** [comment]
the problem will solve itself once we start using the upstream version of the file. The one [currently used for flathub](https://github.com/flathub/org.fontforge.FontForge/blob/e9973e83fc33b1e817c51455070636cad154b972/org.fontforge.FontForge.appdata.xml#) has many translations.  [Upstream has](https://github.com/fontforge/fontforge/blob/d8f1c2ad04de86491a675efb1bf1371cd2727bfa/desktop/org.fontforge.FontForge.appdata.xml.in) moved away from providing translations in the file itself, it seems.

**Comment by jgarciao** [comment]
The translations of the `<p>` tags in the `<description>` are the problem because a of a limitation of the website backend

FontForge has this:
```
 <description>
    <p xml:lang="C">
  FontForge is a font editor for outline and bitmap fonts that lets you create,
  edit, or convert, a range of fonts, including PostScript, TrueType, OpenType,
  cid-keyed, multi-master, cff, SVG and BitMap (bdf, FON, NFNT) fonts.</p>
     ...
    <p xml:lang="fr">FontForge est un éditeur de polices de caractères ...
```

Which seems correct for the appstream spec but the backend doesn't handle the translated `<p`> tags correctly

Other apps like GIMP have the description tag with translations and they are processed fine
```
<description><p>KTouch is a typewriter trainer ...
<description xml:lang="bs"><p>KTouch je trener za učenje kucanja na pisaćoj...
```

So, until the backend is fixed the solution could be adopting the upstream appdata file without translations or change how translations are handled

**Comment by barthalion** [comment]
I mean, I still don't think it's what happens. KTouch also uses `xml:lang` inside `<p>` tags, but the difference is they don't specify `xml:lang="C"` for default English description. Something goes wrong with that in the backend.

**Comment by jgarciao** [comment]
Gnome Software 3.30.6 shows FontForge description in English abut also in my desktop language (Catalan). But for GIMP it just shows the description in Catalan

![gnome-software-FontForge](https://user-images.githubusercontent.com/66894/67380019-0504bf80-f58a-11e9-8a30-f7830782f2d0.png)

**Comment by barthalion** [comment]
I deleted `xml:lang="C"` from appdata file, let's see if that's enough to make it work properly.

**Comment by jgarciao** [comment]
I think the `<description>` will be still too long. The solution is handling the translations like GIMP

**Comment by bilelmoussaoui** [comment]
https://flathub.org/apps/details/org.fontforge.FontForge
